{
 "title": "Windows overview",
 "tags": [ "windows-exporter-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(windows_cs_hostname, job)"
   },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "label_values(windows_cs_hostname{job=~\"$job\"}, hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Integration status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Integration status",
   "type": "stat",
   "description": "Indicates if the agent is configured and sending metrics.",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(windows_cpu_time_total{job=~\"$job\", agent_hostname=~\"$hostname\",mode=\"idle\"})"
    }
   ]
  },
  {
   "title": "Latest metric received",
   "type": "stat",
   "description": "Date and time of the latest metric received from the Windows host",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(windows_cpu_time_total{job=~\"$job\", agent_hostname=~\"$hostname\",mode=\"idle\"})"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Usage",
   "type": "table",
   "description": "Shows overall CPU, memory and disk stats.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "windows_os_info{job=~\"$job\", agent_hostname=~\"$hostname\"} * on(instance) group_right(product) windows_cs_hostname",
     "legendFormat": "group"
    },
    {
     "expr": "100 - (avg by (instance) (rate(windows_cpu_time_total{job=~\"$job\", agent_hostname=~\"$hostname\",mode=\"idle\"}[$__rate_interval])) * 100)",
     "legendFormat": "CPU Usage %"
    },
    {
     "expr": "time() - windows_system_system_up_time{job=~\"$job\", agent_hostname=~\"$hostname\"}",
     "legendFormat": "Uptime"
    },
    {
     "expr": "windows_cs_logical_processors{job=~\"$job\", agent_hostname=~\"$hostname\"} - 0",
     "legendFormat": "CPUs"
    },
    {
     "expr": "windows_cs_physical_memory_bytes{job=~\"$job\", agent_hostname=~\"$hostname\"} - 0",
     "legendFormat": "Memory"
    },
    {
     "expr": "100 - 100 * windows_os_physical_memory_free_bytes{job=~\"$job\", agent_hostname=~\"$hostname\"} / windows_cs_physical_memory_bytes{job=~\"$job\", agent_hostname=~\"$hostname\"}",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "(windows_logical_disk_free_bytes{job=~\"$job\", agent_hostname=~\"$hostname\",volume=~\"C:\"}/windows_logical_disk_size_bytes{job=~\"$job\", agent_hostname=~\"$hostname\",volume=~\"C:\"}) * 100",
     "legendFormat": "C:\\ Free %"
    }
   ]
  },
  {
   "title": "Overview graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU usage % by host",
   "type": "graph",
   "description": "CPU usage % by host, measured by the percentage of time spent not idle over the last $__rate_interval.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (avg by (agent_hostname) ( rate(windows_cpu_time_total{job=~\"$job\", agent_hostname=~\"$hostname\",mode=\"idle\"}[$__rate_interval])) )",
     "legendFormat": "{{agent_hostname}}"
    }
   ]
  },
  {
   "title": "Memory usage % by host",
   "type": "graph",
   "description": "Physical memory usage % by host.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - windows_os_physical_memory_free_bytes{job=~\"$job\", agent_hostname=~\"$hostname\"} / windows_cs_physical_memory_bytes{job=~\"$job\", agent_hostname=~\"$hostname\"}",
     "legendFormat": "{{agent_hostname}}"
    }
   ]
  },
  {
   "title": "Resource details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Uptime by host.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "format": "s",
   "valueName": "avg",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - windows_system_system_up_time{job=~\"$job\", agent_hostname=~\"$hostname\"}"
    }
   ]
  },
  {
   "title": "Services in error",
   "type": "stat",
   "description": "Services in error by host.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "format": "none",
   "valueName": "avg",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(windows_service_status{status=\"error\",job=~\"$job\", agent_hostname=~\"$hostname\"})"
    }
   ]
  },
  {
   "title": "Usage of each partition",
   "type": "bargauge",
   "description": "Disk usage % per partition.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (windows_logical_disk_free_bytes{job=~\"$job\", agent_hostname=~\"$hostname\"} / windows_logical_disk_size_bytes{job=~\"$job\", agent_hostname=~\"$hostname\"})*100",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Disk read write",
   "type": "graph",
   "description": "Disk read and write rate by host.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(windows_logical_disk_write_bytes_total{job=~\"$job\", agent_hostname=~\"$hostname\"}[$__rate_interval])",
     "legendFormat": "write {{volume}}"
    },
    {
     "expr": "rate(windows_logical_disk_read_bytes_total{job=~\"$job\", agent_hostname=~\"$hostname\"}[$__rate_interval])",
     "legendFormat": "read {{volume}}"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "graph",
   "description": "Network usage by host, excluding isatap and VPN interfaces.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(rate(windows_net_bytes_total{job=~\"$job\", agent_hostname=~\"$hostname\",nic!~\"isatap.*|VPN.*\"}[$__rate_interval]) * 8 / windows_net_current_bandwidth{job=~\"$job\", agent_hostname=~\"$hostname\",nic!~\"isatap.*|VPN.*\"}) * 100",
     "legendFormat": "{{nic}}"
    }
   ]
  },
  {
   "title": "IIS connections",
   "type": "graph",
   "description": "The number of active IIS connections by host.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "windows_iis_current_connections{job=~\"$job\", agent_hostname=~\"$hostname\"}",
     "legendFormat": "{{agent_hostname}}"
    }
   ]
  }
 ]
}